services:
  - type: web
    name: words-backend
    runtime: docker
    plan: free
    dockerfilePath: ./deploy/backend.Dockerfile
    dockerContext: .
    envVars:
      - key: FRONTEND_URL
        value: https://words-frontend.onrender.com
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: words-db
          property: connectionString

databases:
  - name: words-db
    plan: free
